FROM node:20-alpine AS deps

WORKDIR /app

COPY package*.json ./
RUN npm install

FROM node:20-alpine AS builder

WORKDIR /app

ARG DATABASE_URL
ARG JWT_SECRET
ARG JWT_EXPIRES_IN
ARG PORT
ARG CORS_ORIGIN
ARG CORS_ORIGINS

ENV DATABASE_URL=$DATABASE_URL
ENV JWT_SECRET=$JWT_SECRET
ENV JWT_EXPIRES_IN=$JWT_EXPIRES_IN
ENV PORT=$PORT
ENV CORS_ORIGIN=$CORS_ORIGIN
ENV CORS_ORIGINS=$CORS_ORIGINS
ENV NODE_ENV=production

COPY --from=deps /app/node_modules ./node_modules
COPY . .

RUN npm run build

FROM node:20-alpine AS runner

WORKDIR /app

ARG DATABASE_URL
ARG JWT_SECRET
ARG JWT_EXPIRES_IN
ARG PORT
ARG CORS_ORIGIN
ARG CORS_ORIGINS

ENV NODE_ENV=production
ENV PORT=3000
ENV DATABASE_URL=$DATABASE_URL
ENV JWT_SECRET=$JWT_SECRET
ENV JWT_EXPIRES_IN=$JWT_EXPIRES_IN
ENV CORS_ORIGIN=$CORS_ORIGIN
ENV CORS_ORIGINS=$CORS_ORIGINS

COPY --from=builder /app/package*.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public

EXPOSE 3000

CMD ["npm", "run", "start"]